### ISSUE TITLE
[EGeneral:Internal error]

### ISSUE THREAD

**Issue by spikeruk** [scionaltera/arbitrader#184]
Any idea why this error would happen for info.bitrich.xchangestream.kraken.KrakenStreamingExchange?

2020-06-21 18:35:47.142  INFO 1804 --- [           main] com.r307.arbitrader.Arbitrader           : Starting Arbitrader on Cube-PC with PID 1804 (C:\Arbitrage\arbitrader\bin\main started by user in C:\Arbitrage\arbitrader)
2020-06-21 18:35:47.149  INFO 1804 --- [           main] com.r307.arbitrader.Arbitrader           : No active profile set, falling back to default profiles: default
2020-06-21 18:35:49.358  INFO 1804 --- [           main] i.b.x.kraken.KrakenStreamingExchange     : Calling Remote Init...
2020-06-21 18:35:51.119  INFO 1804 --- [           main] o.k.x.coinbasepro.CoinbaseProExchange    : Calling Remote Init...
2020-06-21 18:35:51.632  WARN 1804 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tradingService': Invocation of init method failed; nested exception is org.knowm.xchange.exceptions.ExchangeException: [EGeneral:Internal error]
2020-06-21 18:35:51.765 ERROR 1804 --- [           main] o.s.boot.SpringApplication               : Application run failed

**Comment by scionaltera** [comment]
I can’t tell from that since there’s no stack trace. Can you send me a copy
of your application.yaml with the API keys removed? It might be a missing
option or a typo or something like that.

Also make sure you check the “important note for windows users” here if you
haven’t already. Otherwise Docker might not mount your config file into the
volume on the container.

https://github.com/scionaltera/arbitrader/wiki/Using-Arbitrader

**Comment by spikeruk** [comment]
It connects to other exchanges fine.

I just get that error for Kraken. (Though my account isn't margin enabled, not sure that matters just to get the app started?)

I am using the sample YAML file for Kraken, I just inserted my API key & secret

**Comment by spikeruk** [comment]
Fails at this line for Kraken

for (Wallet wallet : accountService.getAccountInfo().getWallets().values()) {

**Comment by scionaltera** [comment]
> Fails at this line for Kraken
> 
> for (Wallet wallet : accountService.getAccountInfo().getWallets().values()) {

Please double check that:

1) Your Kraken account is funded with USD (or you have specified a different home currency and THAT is funded).
2) Your API key for Kraken is allowed to access your wallets and account balances.
3) If you are NOT using Kraken for margin trading that you have NOT set `margin: true`.

My best guess is that `getWallets()` is returning null for some reason. Could be anything from "there is no such account" to "there is no currency of that type in the account" or anything in between.

As a side note, the fact that it returns null instead of an empty collection is a bug in my opinion, but that code lives in XChange, not Arbitrader.

**Comment by spikeruk** [comment]
It actually fails at accountService.getAccountInfo()
The account is not funded, but don't think it needs to be at the stage of the app starting up (obviously to place a trade it would need to be)

Loving the learning from this.
I am big in cryptocurrencies, but never really shorted before so this is helpful to learn.
And does have a fun element to it as well!

On average have you made any money with it? or is it just a novelty?

**Comment by spikeruk** [comment]
Do you have Kraken configured?

- I've tried with both Margin: true and false
- All API key functionalities are enabled

Now trying to KYC my account with Kraken in case it doesn't work on Tier 1 account.

**Comment by scionaltera** [comment]
> It actually fails at accountService.getAccountInfo()
> The account is not funded, but don't think it needs to be at the stage of the app starting up

I think it's possible for Kraken to report not having a wallet at all if it just isn't funded, especially if it has never been funded. Arbitrader doesn't care until it tries to trade but it may affect how the Kraken API reports data back to XChange or how XChange interprets a zero balance wallet.

https://github.com/knowm/XChange/blob/develop/xchange-kraken/src/main/java/org/knowm/xchange/kraken/service/KrakenAccountService.java#L43-L54

XChange's strength is that it provides a common API but its weakness is that not all of the implementations of the contract behave the same because it's an abstraction over things that are fundamentally different from one another.

Try throwing a couple bucks into the account and see if that resolves the issue. You shouldn't even need enough to trade, just a non-zero balance to create the wallet.

> Loving the learning from this.
> I am big in cryptocurrencies, but never really shorted before so this is helpful to learn.
> And does have a fun element to it as well!

Glad you're having fun! It's a neat strategy, and not one that a lot of people have tried.

> On average have you made any money with it? or is it just a novelty?

So this is not a get-rich-quick trading strategy. It's slow and steady, and very low risk. My personal experience is that I'm almost always running a development branch of the bot. I restart it a lot, I rebalance my accounts a lot, and the majority of the time I get failed trade executions or other conditions where it didn't do what it should have done, because most of the time I'm testing something new or debugging something. So I'm not sure overall whether I'm ahead of where I started. I can confidently say I still have enough cash in my accounts to trade with. Typically when I'm testing a branch I let it run until it makes a successful trade or two, proving the new code works, and then I'm off to the next feature. I don't have enough trading cash to run both an "investment" and a "development" copy of the bot, so I just do the part I think is fun. :D

I do think if you had sufficiently large accounts and the patience to just let it run you would see gains that would make it worthwhile. I rarely see a trade that results in a loss and when I do it's almost always a bug in new code I'm testing. My accounts are such that on a successful transaction I only make a few bucks so it's not like I'm going to quit my day job any time soon.

I'll also throw in that it's a v0.x.x version still. I don't consider it reliable enough yet that you can just turn it on and let it run forever. It needs a lot more bulletproofing around general API failures. For instance if it tries to close a position and the exchange throws some kind of "I'm too busy, try again later" exception it won't try again. It just exits and you have to go close out the position yourself. If it somehow opens two trades it doesn't yet know how to inspect the exchange and close the duplicate. Those are both solvable problems that will be solved and it will some day get to a point where you can just turn it on and walk away, but there's still a lot left to do.

**Comment by spikeruk** [comment]
I'll fund the Kraken account and keep you updated.
Congrats on getting the application this far!

When more exchanges adopt the lightning network it could open some very interesting arbitrage opportunities as then you can pass cryptocurrencies between exchanges with speed and virtually no cost. Then when an arbitrage opportunity opens itself you could for example buy BTC on one exchange, and quickly send it to another and sell.
https://medium.com/@cointastical/exchanges-with-support-for-bitcoin-lightning-network-payments-739829bcb7bc

**Comment by scionaltera** [comment]
Sure, that's a more traditional arbitrage.

The simplest example is buying for cheap on one exchange, transferring to another and selling high there. Right now the risk there is it takes so long to transfer that you could miss your window of opportunity. Lightning could help close that problem and you'd definitely want a bot to orchestrate the trade, transfer and trade faster than everyone else can do it.

The next version of that is maintaining accounts funded in both fiat and crypto on both exchanges and simultaneously buying cheap and selling high, then rebalancing your accounts later. The drawback of course is that you have to fund a lot of accounts with a substantial amount of cash in both currencies, and holding crypto exposes you to a lot more fluctuation.

That's the main reason Arbitrader's strategy appealed to me. The default state is all USD where it's less likely to lose value and you only get crypto when you're very sure you can make money from it. The only other strategy that makes sense to me personally is just holding BTC for the long term. Not financial advice of course, just some random guy on the internet with an opinion. :)

**Comment by spikeruk** [comment]
If I set margin: true

Does that exchange get checked as a possible long trade AND possible short trade?
or if margin: true for all configured changes will it never place a trade? (as its only looking for possible short trades)

**Comment by scionaltera** [comment]
> If I set margin: true
> 
> Does that exchange get checked as a possible long trade AND possible short trade?
> or if margin: true for all configured changes will it never place a trade? (as its only looking for possible short trades)

Margin exchanges can be used for both long and short trades. For awhile I was running Kraken and Liquid, both of which support margin. Sometimes Kraken would be short, other times Liquid would be. Unfortunately Liquid is no longer supporting US based customers so I'm down to just one margin exchange now. :-\

**Comment by spikeruk** [comment]
I have 4 exchanges going (Polonix, Coinbase, Kraken, Liquid)
Haven't got any hits in a few days so was wondering if something was wrong, but not sure how often it matches an arb.
Had one match at the start of the week but I was in debug mode just learning the code so didn't let it execute.

**Comment by scionaltera** [comment]
How often it trades depends entirely on how it's configured and market conditions. The default entry and exit settings are what I use and lately it hasn't been trading at all for me. I've also had days and weeks where it traded constantly. That happens when there's a lot of volatility and the markets are changing prices sharply.

You can narrow your entry/exit but there are consequences:

A smaller `entrySpread` makes it enter trades more easily, but it still has to get to `entrySpread - exitTarget - fees` to close. So you can easily get into a scenario where it enters trades but will never exit because the target is unrealistic.

A smaller `exitTarget` makes it exit trades more easily, but that target directly represents your profit. Making it smaller will make your profit smaller. Making it bigger will get more profit per trade, but the target gets harder (or impossible!) to achieve.

If you're just testing with $20 or $30 in each account and you want to see it trade more than you want to make profit, set your `entrySpread` and `exitTarget` lower. Ideally you want to understand the range of spreads the market is trading in right now. Set `entrySpread` to the top of that range and `exitTarget` to somewhat less than the width of that range.

In the current version there is a daily summary of the min/max `spreadIn`s and `spreadOut`s the bot has seen so far. Here's how you can use those to tune your `entrySpread` and `exitTarget`.

The values you need are the maximum `spreadIn`s and the minimum `spreadOut`s. Those are what you have to hit to enter and exit trades, respectively. So if you run the bot for a few days and you see that it never got a `spreadIn` above 0.006 you could try setting it to 0.005 to make sure it trades. If you see `spreadOut`s never went below 0.000 then you know you will enter trades at 0.005, you need to exit at 0.000, so try an `exitTarget` of 0.002 or 0.003 - you'll only get a little bit of profit (fees get added in too between that 0.000 and 0.006 range) but it should trade more frequently within that range.

In that example you also know that the markets' range is pretty narrow for this kind of trading strategy right now. It won't stay that way forever, so patience is key. Trading isn't about excitement and the bot isn't trading because there aren't any opportunities. For me personally, I built a bot because I'm not good at sitting watching charts and _not_ trading, but my computer is happy to do it for me.

**Comment by scionaltera** [comment]
I'm going to go ahead and close this for now.
