### ISSUE TITLE
Margin Exchanges

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#256]
How many margin exchanges do we need ?
Poloniex and Bianance support margin trading too. Can we add them safely ?

**Comment by scionaltera** [comment]
I have personally used Kraken, Poloniex and Liquid (Quoine) for margin trading. There is an issue open #255 to test Binance but I haven't been able to use it myself since I don't have an account there. If you do try out Binance and get it to work please contribute your configuration (without your API keys, of course :D) so others can use that exchange too. If you don't want to be the first, I am planning to open an account and try it out at some point soon to close that ticket.

You only _need_ one exchange that supports margin to make trades, but having more will open more opportunities.

**Comment by sanitariu** [comment]
Margin option is false at poloniex. Does margin works there ? I have account at binance will try there. Margin probably works there too ?

**Comment by scionaltera** [comment]
I haven't used margin at Poloniex and I can't test it myself because they stopped supporting customers from the US. If you are able to test margin at Poloniex and Binance that would be a huge help. :)

**Comment by sanitariu** [comment]
I am going to try poloniex/liquid - both margin + bitstamp with real money.
Any bugs/crashes i will report here
