### ISSUE TITLE
Adding new exchanges

### ISSUE THREAD

**Issue by sanitariu** [scionaltera/arbitrader#69]
Do you plan adding new exchanges like bitstamp or others ?
Personally i can test on bitstamp if you need real account.....
Also bitfinex is okay but some crypto prices there are really weird ?!...

**Comment by scionaltera** [comment]
Arbitrader uses an open source project called [knowm/XChange](https://github.com/knowm/XChange) to connect to exchanges. It provides a common interface to 60+ different exchanges. Each one is implemented as a separate module, so I have only added the ones that I have actually tried.

Here are the steps to add the new module and build a new Docker container:

1. Check that XChange has a module for the exchange you want. It will be called `xchange-<exchange name>`.
1. Create an API key with the new exchange if you don't already have one.
1. In `build.gradle` find the part where it imports the dependencies from XChange (around line 40), follow the pattern and add a line for the new exchange.
1. Run `./gradlew clean build` to recompile the project, run the tests and make a new Docker container.
1. Add the configuration for your new exchange to `application.yaml`.
1. Run `docker-compose up` and see if your new exchange works.

Unfortunately I can't provide a lot of support for exchanges that I don't use. Some of the XChange implementations are in progress or otherwise incomplete, and some lack features that Arbitrader requires. I have personally had to contribute some code back to XChange to get the exchanges I wanted to use to work.

Some exchanges have unique requirements for authentication or other configuration (like Coinbase Pro's "passphrase") so you may run into some difficulties like that but it's certainly worth a try.

If you do get set up other exchanges that work I'd always appreciate a pull request back to this project to add the dependency in `build.gradle` and a sample configuration in `application.example.yaml`.

**Comment by sanitariu** [comment]
Ok i am trying some but it is difficult really. I noticed maybe a small bug like starting trade even when balance is $0.
Here is the log:
arbitrader_1  | 2019-04-14 11:36:18.137  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : ***** ENTRY *****
arbitrader_1  | 2019-04-14 11:36:19.621  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Updated account balances: Cryptopia $0.00 + Kraken $43.31 = $43.31
arbitrader_1  | 2019-04-14 11:36:19.758  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Entry spread: 0.39542700
arbitrader_1  | 2019-04-14 11:36:19.894  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exit spread target: -0.01477300
arbitrader_1  | 2019-04-14 11:36:20.033  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Long entry: Cryptopia BTC/USD 0.00027548 @ 3630.00000000 (0E-8 slip) = $0.9999924000000000
arbitrader_1  | 2019-04-14 11:36:20.170  INFO 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Short entry: Kraken BTC/USD 0.00019742 @ 5064.80000 (0.60000 slip) = $0.9998928160000
arbitrader_1  | 2019-04-14 11:36:20.533 ERROR 1 --- [   scheduling-1] c.r.arbitrader.service.TradingService    : Exchange returned an error executing trade!
arbitrader_1  |
arbitrader_1  | org.knowm.xchange.exceptions.ExchangeException: Invalid trade amount, Minimum total trade is 1.00000000 USDT


Maybe we should not place order if balance is $0 ?
Actually cryptopia is not working from 2 days and i can not test it.
Will look for other exchanges....

**Comment by scionaltera** [comment]
Fixed the $0 trades and explained how to add new exchanges in the [documentation](https://github.com/scionaltera/arbitrader/wiki/Adding-New-Exchanges) and the [CONTRIBUTING doc](https://github.com/scionaltera/arbitrader/blob/master/CONTRIBUTING.md#add-exchanges).
